### ISSUE TITLE
Error when running wishlist.py with an empty wishlist.txt file.

### ISSUE THREAD

**Issue by pi6220na** [claraj/book_wishlist#11]
If you run the wishlist.py program and don't add anything and just quit the program, the next time you run the program an array bounds exception due to an empty wishlist.txt file occurs (line 109 datastore.py). Deleting the two .txt files created from the first execution solves the problem. Rerunning with no .txt files allows the program to run cleanly and I was able to add a book title and author which was then saved into the wishlist.txt file, and the counter.txt file was also created correctly.
- Jeremy Wolfe
- 1/18/2018

**Comment by justint1me** [comment]
# function for the setup of getting the books from a file
def setup():
    ''' Read book info from file, if file exists. '''

    # calling the global variable counter
    global counter

    # try except action to see if there is a file on the system
    try :
        with open(BOOKS_FILE_NAME) as f:
            # fix for trying to read empty file and throwing IndexError
            if os.stat(BOOKS_FILE_NAME).st_size==0:
                pass
            else:
                data = f.read()
                make_book_list(data)
    except FileNotFoundError:
        # First time program has run. Assume no books.
        pass

    # try except action to see how many books are saved
    try:
        with open(COUNTER_FILE_NAME) as f:
            try:
                counter = int(f.read())
            except:
                counter = 0
    except:
        counter = len(book_list)

**Comment by justint1me** [comment]
I had this same issue and solved it. The code above shows the change I made in the fix. On the first try except block you must check if the file is empty, and if it is type pass, just like Clara did under the first time program run.

**Comment by justint1me** [comment]
I found that this issue kept coming back up when I was working on the first two issues, but since the fix I have had no further problems.

**Comment by claraj** [comment]
Thanks both. Fixed with 9414b39
